import { useState } from 'react'
import media from '@/data/media.json'
import sourced from '@/data/media-sourced.json'

interface Entry {
  name: string
  folder: string
  widths: number[]
  w: number
  h: number
  ratio: number
  color: string
  alt: string
}

/**
 * Two registries, one lookup.
 *
 * `media.json` is generated by `tools/assets.py` from the six company profile
 * PDFs — it is the site's own photography and must not be hand-edited.
 * `media-sourced.json` is hand-authored and holds the stock-licensed frames
 * used where the profiles had no photograph of a line of work. Keeping them in
 * separate files is what keeps that distinction checkable: `image-credits.json`
 * carries a licence record for every key in the second file and none in the
 * first.
 */
const REGISTRY = { ...media, ...sourced } as Record<string, Entry>

export interface MediaSource {
  src: string
  srcSet: string
  alt: string
  /** Dominant colour, for holding the box before the file lands. */
  color: string
  /** Width over height. Lets a caller judge how a frame will crop it. */
  ratio: number
}

/**
 * Resolves a registry key to the same responsive set `Media` renders.
 *
 * `Media` owns the common case. This exists for the places that need the URLs
 * without the element — a component that draws its own `<img>` because it also
 * animates the frame around it, for instance — so those places still ship the
 * WebP set rather than hotlinking one large file.
 */
export function mediaSource(src: string): MediaSource | null {
  const entry = REGISTRY[src]
  if (!entry) return null

  const base = `/media/${entry.folder}/${entry.name}`
  const largest = entry.widths[entry.widths.length - 1]

  return {
    src: `${base}-${largest}.webp`,
    srcSet: entry.widths.map((w) => `${base}-${w}.webp ${w}w`).join(', '),
    alt: entry.alt,
    color: entry.color,
    ratio: entry.ratio,
  }
}

interface MediaProps {
  /** Key into the media registry, e.g. `developers/tower-lineman`. */
  src: string
  /** Overrides the alt text recorded with the asset. */
  alt?: string
  className?: string
  /** `sizes` attribute — always give the browser a real hint. */
  sizes?: string
  priority?: boolean
  /** Renders the intrinsic aspect ratio instead of filling its parent. */
  intrinsic?: boolean
}

/**
 * Responsive picture backed by the generated WebP set.
 *
 * Every asset ships at up to three widths with a recorded aspect ratio and
 * dominant colour, so the box is reserved before the file lands and nothing
 * shifts as images stream in.
 */
export function Media({
  src,
  alt,
  className = '',
  sizes = '100vw',
  priority = false,
  intrinsic = false,
}: MediaProps) {
  const entry = REGISTRY[src]
  const [loaded, setLoaded] = useState(false)

  if (!entry) return null

  const base = `/media/${entry.folder}/${entry.name}`
  const srcSet = entry.widths.map((w) => `${base}-${w}.webp ${w}w`).join(', ')
  const largest = entry.widths[entry.widths.length - 1]

  return (
    <img
      src={`${base}-${largest}.webp`}
      srcSet={srcSet}
      sizes={sizes}
      alt={alt ?? entry.alt}
      width={entry.w}
      height={entry.h}
      loading={priority ? 'eager' : 'lazy'}
      // fetchPriority nudges the LCP image ahead of the rest of the queue
      fetchPriority={priority ? 'high' : 'auto'}
      decoding={priority ? 'sync' : 'async'}
      onLoad={() => setLoaded(true)}
      style={{
        backgroundColor: loaded ? undefined : entry.color,
        aspectRatio: intrinsic ? `${entry.w} / ${entry.h}` : undefined,
      }}
      className={[
        intrinsic ? 'w-full h-auto' : 'h-full w-full object-cover',
        'transition-opacity duration-700 ease-out',
        loaded ? 'opacity-100' : 'opacity-0',
        className,
      ].join(' ')}
    />
  )
}
