"""
Company-supplied portraits.

A third provenance category, kept apart from the other two on purpose:

  media.json          the six profile PDFs, generated by assets.py
  media-sourced.json  stock-licensed frames, one credit each in image-credits.json
  media-supplied.json this file's output — portraits handed over by the company

`assets.py` cannot carry these. It rewrites the whole of `media.json` from
`.dist/extract`, which only exists while the source PDFs are unpacked, so a
portrait added there by hand is dropped the next time anyone runs it.

Unlike `assets.py`, this one is repeatable from a clean checkout: the originals
are committed under `tools/source/team/`, named for the registry key they
become. To add a member, drop `<key>.jpeg` in that folder, add a line to
PORTRAITS with the alt text, and re-run from the project root:

    python tools/team.py

Requires Pillow.
"""

from PIL import Image, ImageOps
import os, json, colorsys

OUT = 'public/media/group'
SRC = 'tools/source/team'
WIDTHS = [480, 640]


def dominant(im):
    """Dominant colour, held behind the frame until the file lands.

    Same sampling as assets.py — near-white is skipped so a studio backdrop
    does not flatten every portrait to the same grey, and lightness is capped
    so the holding colour reads as a shadow rather than a flash.
    """
    s = im.convert('RGB').resize((48, 48), Image.BILINEAR)
    tot = [0, 0, 0]
    n = 0
    for r, g, b in (s.get_flattened_data() if hasattr(s, 'get_flattened_data') else list(s.getdata())):
        if r > 247 and g > 247 and b > 247:
            continue
        tot[0] += r; tot[1] += g; tot[2] += b; n += 1
    if not n:
        return '#1a1a1a'
    r, g, b = [v // n for v in tot]
    h, l, s2 = colorsys.rgb_to_hls(r / 255, g / 255, b / 255)
    l = min(l, 0.42)
    r, g, b = [int(v * 255) for v in colorsys.hls_to_rgb(h, l, s2)]
    return '#%02x%02x%02x' % (r, g, b)


PORTRAITS = [
    ('datta-bamane', 'Portrait of Mr. Datta Bamane'),
    ('chindanand-hiremath', 'Portrait of Mr. Chindanand Hiremath'),
]

manifest = {}
os.makedirs(OUT, exist_ok=True)

for name, alt in PORTRAITS:
    src = SRC + '/' + name + '.jpeg'
    im = ImageOps.exif_transpose(Image.open(src)).convert('RGB')
    W, H = im.size
    widths = []
    for w in WIDTHS:
        # Never upscale. A phone-sized original stays its own size rather than
        # being interpolated up to a width it has no detail for.
        if w > W and widths:
            break
        w = min(w, W)
        if w in widths:
            continue
        r = im.resize((w, max(1, round(H * w / W))), Image.LANCZOS)
        r.save('%s/%s-%d.webp' % (OUT, name, w), 'WEBP', quality=86, method=6)
        widths.append(w)
    manifest['group/' + name] = {
        'name': name, 'folder': 'group', 'widths': widths, 'w': W, 'h': H,
        'ratio': round(W / H, 4), 'color': dominant(im), 'alt': alt,
    }
    print('%-30s %dx%d %s' % (name, W, H, widths))

json.dump(manifest, open('src/data/media-supplied.json', 'w'), indent=1)
print('\nsupplied: %d' % len(manifest))
